services:
  app_flask_quickstart:
    pull_policy: build
    image: app_flask_quickstart:latest
    volumes:
      - .:/app_flask_quickstart
    build:
      dockerfile: Dockerfile.dev
    network_mode: service:postgres_service
    # if you want to edit outside a devcontainer,uncomment the "ports" config below AND comment out "network_mode: service:postgres_service"
    # ports:
      # - "8080:8080"
    depends_on:
      postgres_service:
        condition: service_healthy
  postgres_service:
    extends:
      file: docker-compose-common.yml
      service: postgres_service
