FROM mcr.microsoft.com/devcontainers/python:3.11

EXPOSE 8080

WORKDIR /app_flask_quickstart

ENV PYTHONUNBUFFERED=1

COPY . .

RUN python -m pip install -r requirements.dev.txt

RUN adduser -u 5678 --disabled-password --gecos "" app_flask_quickstart && chown -R app_flask_quickstart /app_flask_quickstart
USER app_flask_quickstart

RUN chmod +x ./entrypoint.dev.sh

ENTRYPOINT [ "./entrypoint.dev.sh" ]
