services:
  app_flask_quickstart:
    pull_policy: build
    image: app_flask_quickstart:latest
    volumes:
      - .:/app_flask_quickstart
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
      - 5678:5678
    depends_on:
      postgres_service:
        condition: service_healthy
    # This adds debugpy to the environment so you can debug the app
    entrypoint: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run"]
    environment:
      - FLASK_APP=src/app_flask_quickstart/app.py

  postgres_service:
    extends:
      file: docker-compose-common.yml
      service: postgres_service