services:
  app_etl:
    pull_policy: build
    image: app_etl:latest
    volumes:
      - .:/app_etl
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 5678:5678
    depends_on:
      postgres_service:
        condition: service_healthy
    # This adds debugpy to the environment so you can debug the app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 8080"]
    environment:
      - FLASK_APP=src/app_etl/app.py

  postgres_service:
    extends:
      file: docker-compose-common.yml
      service: postgres_service
  app_x_database_flyway_migrations:
    extends:
      file: docker-compose-common.yml
      service: app_x_database_flyway_migrations