services:
  app_flask_archetype_postgres_service:
    image: postgres:17
    container_name: "app_flask_archetype_postgres_service"
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file:
      - .env
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./app_flask_archetype_data/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PASSWORD} -p ${POSTGRES_PORT}" ]
      start_period: 0s
      interval: 10s
      timeout: 30s
      retries: 3
