services:
  app_flask_archetype:
    image: app_flask_archetype:latest
    volumes:
      - .:/app_flask_archetype
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
      - 5678:5678
    depends_on:
      postgres_service:
        condition: service_healthy
    entrypoint: ["sh", "-c", "python /usr/local/bin/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run"]
    environment:
      - FLASK_APP=src/app_flask_archetype/app.py
      - POSTGRES_HOST=postgres_service
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app_flask_archetype
      - POSTGRES_USER=app_flask_archetype
      - POSTGRES_PASSWORD=postgres
      - PORT=5000
  postgres_service:
    extends:
      file: docker-compose-common.yaml
      service: postgres_service