services:
  app_flask_archetype:
    image: app_flask_archetype:latest
    volumes:
      - .:/app_flask_archetype
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
      - 5678:5678
    depends_on:
      app_flask_archetype_postgres_service:
        condition: service_healthy
    entrypoint: [ "sh", "-c", "python /usr/local/bin/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run" ]
    environment:
      - FLASK_APP=${FLASK_APP}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PORT=$(APPLICATION_PORT)
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file:
      - .env
  app_flask_archetype_postgres_service:
    extends:
      file: docker-compose-common.yaml
      service: app_flask_archetype_postgres_service
