name: app_flask_archetype

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.11", "3.12.8", "3.13.1"]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.dev.txt

      - name: Run Test
        run: pytest

      - name: Spell Check
        uses: rojopolis/spellcheck-github-actions@0.45.0
        with:                                        
          output_file: spellcheck-output.txt
